#!/bin/bash
# Converts AWS env. variables from lambda or elastic beanstalk (todo) to export statements.

set -e
IFS=$'\n\t'

AWS_PROFILE=""
NAME=""
MODE="lambda"

while [[ $# > 0 ]]
do
    key="$1"
    value="$2"

    case $key in
        -p)
            AWS_PROFILE=$value
            shift
            ;;
        --profile)
            AWS_PROFILE=$value
            shift
            ;;
        -l)
            MODE="lambda"
            ;;
        --lambda)
            LOGIN=true
            ;;
        -e)
            MODE="eb"
            ;;
        --elastic-beanstalk)
            MODE="eb"
            ;;
        --ssm)
            MODE="ssm"
            ;;
        -n)
            NAME=$value
            shift
            ;;
        --name)
            NAME=$value
            shift
            ;;
        -h)
            echo "Configurable options: -n <NAME>"
            echo "Boolean flags: -l (lambda) ; -e (elastic beanstalk) -s (source env. vars)"
            exit 1
            ;;
        --help)
            echo "Configurable options: -n <NAME>"
            echo "Boolean flags: -l (lambda) ; -e (elastic beanstalk) -s (source env. vars)"
            exit 1
            ;;
        -v)
            set -x
            ;;
        *)
            echo "Unknown option passed: $key"
            exit 1
            ;;
    esac
    shift
done

if [ "$NAME" == "" ]; then
  echo "Missing name: option -n <NAME>"
  exit 1
fi

main() {

  aws_profile_option=""
  if [ "$AWS_PROFILE" != "" ]; then
    aws_profile_option=" --profile $AWS_PROFILE "
  fi
  
  if [ "$MODE" == "lambda" ]; then
    run_command="aws $aws_profile_option lambda get-function-configuration --function-name \"$NAME\" | jq -r '.Environment.Variables | to_entries | map(\"export \" + .key + \"=\" + .value) | .[]'"
    output=`eval $run_command`
    echo "$output"
  elif [ "$MODE" == "eb" ]; then
    run_command="aws $aws_profile_option elasticbeanstalk describe-environments --environment-names $NAME | jq -r '.Environments[0][\"ApplicationName\"]'"
    appliction_name=`eval $run_command`
    run_command="aws $aws_profile_option elasticbeanstalk describe-configuration-settings --application-name $appliction_name --environment-name $NAME | jq -r '[ .ConfigurationSettings[0].OptionSettings[] ] | map(select(.Namespace == \"aws:elasticbeanstalk:application:environment\")) | map(\"export \" + .OptionName + \"=\" + .Value) | .[]'"
    output=`eval $run_command`
    echo "$output"
  elif [ "$MODE" == "ssm" ]; then
    #run_command="aws $aws_profile_option ssm get-parameters-by-path --path \"$NAME\""
    run_command="aws $aws_profile_option ssm get-parameters-by-path --path \"$NAME\" | jq -r '.Parameters | map({ Name: (.Name | split(\"/\") | .[-1]), Value: .Value}) | map(\"export \" + .Name + \"=\\\"\" + .Value + \"\\\"\") | .[]'"
    output=`eval $run_command`
    echo "$output"
  else
    echo "Unknown mode: $MODE. Supported modes: 'eb', 'lambda', 'ssm'"
  fi

}

main
