#!/bin/bash

IMAGE_ID=`docker images | head -n 2 | grep -v REPOSITORY | tr -s ' ' | cut -d ' ' -f3`
if [ -n "$1" ]; then
    IMAGE_ID="$1"
fi


CONT_ID=`docker run -idt $IMAGE_ID /bin/bash`


function clean {
  docker rm -f $CONT_ID
}
trap clean EXIT

docker exec -it $CONT_ID /bin/bash
